version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
  backend:
    build:
      context: ./django
    command: gunicorn trajectory.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_dist:/frontend
  nginx:
    image: nginx:latest
    ports: 
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_dist:/var/www/frontend
    depends_on:
      - backend
      - frontend

volumes:
  frontend_dist:
  postgres: